-- MySQL Script generated by MySQL Workbench
-- Sun Jan 26 18:03:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crewconnect
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crewconnect` ;

-- -----------------------------------------------------
-- Schema crewconnect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crewconnect` DEFAULT CHARACTER SET utf8 ;
USE `crewconnect` ;

-- -----------------------------------------------------
-- Table `crewconnect`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crewconnect`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `age` INT NULL,
  `biographie` VARCHAR(255) NULL,
  `mdp` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crewconnect`.`announce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crewconnect`.`announce` (
  `announce_id` INT NOT NULL AUTO_INCREMENT,
  `texte` VARCHAR(255) NULL,
  `date` DATE NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`announce_id`, `user_user_id`),
  INDEX `fk_announce_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_announce_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `crewconnect`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crewconnect`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crewconnect`.`message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL,
  `sent_date` DATE NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`message_id`, `user_user_id`),
  INDEX `fk_message_user_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `crewconnect`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crewconnect`.`domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crewconnect`.`domain` (
  `domain_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  PRIMARY KEY (`domain_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crewconnect`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crewconnect`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `domain_domain_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `domain_domain_id`),
  INDEX `fk_category_domain1_idx` (`domain_domain_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_domain1`
    FOREIGN KEY (`domain_domain_id`)
    REFERENCES `crewconnect`.`domain` (`domain_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `domain` (`domain_id`, `nom`) VALUES
                                              (1, 'Musique'),
                                              (2, 'Cinéma'),
                                              (3, 'Sport'),
                                              (4, 'Lecture'),
                                              (5, 'Informatique'),
                                              (6, 'Gaming');

COMMIT;
-- -----------------------------------------------------
-- Table `crewconnect`.`user_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crewconnect`.`user_has_category` (
  `user_user_id` INT NOT NULL AUTO_INCREMENT,
  `category_category_id` INT NOT NULL,
  `category_domain_domain_id` INT NOT NULL,
  PRIMARY KEY (`user_user_id`, `category_category_id`, `category_domain_domain_id`),
  INDEX `fk_user_has_category_category1_idx` (`category_category_id` ASC, `category_domain_domain_id` ASC) VISIBLE,
  INDEX `fk_user_has_category_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_category_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `crewconnect`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_category_category1`
    FOREIGN KEY (`category_category_id` , `category_domain_domain_id`)
    REFERENCES `crewconnect`.`category` (`category_id` , `domain_domain_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crewconnect`.`notification_announce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crewconnect`.`notification_announce` (
  `notification_announce_id` INT NOT NULL AUTO_INCREMENT,
  `announce_announce_id` INT NOT NULL,
  `announce_user_user_id` INT NOT NULL,
  PRIMARY KEY (`notification_announce_id`, `announce_announce_id`, `announce_user_user_id`),
  INDEX `fk_notification_announce_announce1_idx` (`announce_announce_id` ASC, `announce_user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_notification_announce_announce1`
    FOREIGN KEY (`announce_announce_id` , `announce_user_user_id`)
    REFERENCES `crewconnect`.`announce` (`announce_id` , `user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crewconnect`.`notification_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crewconnect`.`notification_user` (
  `notification_user_id` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`notification_user_id`, `user_user_id`),
  INDEX `fk_notification_user_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_notification_user_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `crewconnect`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
